package RegistrationGUI;

import Clases.Main;
import Clases.User;
import TasksGUI.Dashboard;
import java.awt.*;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.*;
import javax.swing.border.LineBorder;

public class MainWindow extends javax.swing.JFrame {
    
    public MainWindow() {
        initComponents();
        try {
            InputStream is = getClass().getResourceAsStream("/Resources/Fonts/Notedry.ttf");
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, is);
            fuente = fuente.deriveFont(80f);
            loginLbl.setFont(fuente);
            registerLbl.setFont(fuente);

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
        }
        configBtn(logBtn);
        configBtn(registerBtn);
        configBtn(hasAccBtn);
        configBtn(noAccBtn);
        regPanel.setVisible(false);
        logPanel.setVisible(true);
    }

    private void configBtn(javax.swing.JButton btn) {
        btn.setContentAreaFilled(false);
        btn.setBorderPainted(true);
        btn.setFocusPainted(false);
        btn.setOpaque(false);
    }

    private User buscarUsuario(String nombre, String password) {
        for (User u : Main.users) {
            if (u.getNombre().equals(nombre.trim()) && u.getPassword().equals(password)) {
                return u;
            }
        }
        
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logPanel = new javax.swing.JPanel();
        loginLbl = new javax.swing.JLabel();
        logBtn = new javax.swing.JButton();
        loginNameLbl = new javax.swing.JLabel();
        logNameField = new javax.swing.JTextField();
        loginPassLbl = new javax.swing.JLabel();
        logPassField = new javax.swing.JPasswordField();
        showLoggedPassword = new javax.swing.JCheckBox();
        errorLbl = new javax.swing.JLabel();
        noAccBtn = new javax.swing.JButton();
        regPanel = new javax.swing.JPanel();
        registerLbl = new javax.swing.JLabel();
        hasAccBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        registerNameLbl = new javax.swing.JLabel();
        registerNameField = new javax.swing.JTextField();
        newPassField = new javax.swing.JPasswordField();
        newPassLbl = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        errorRegistrationLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Tareas");
        setMaximumSize(new java.awt.Dimension(924, 556));
        setMinimumSize(new java.awt.Dimension(924, 556));
        setResizable(false);

        logPanel.setBackground(new java.awt.Color(0, 0, 0));
        logPanel.setMaximumSize(new java.awt.Dimension(924, 556));
        logPanel.setMinimumSize(new java.awt.Dimension(924, 556));

        loginLbl.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLbl.setText("LOGIN");

        logBtn.setBackground(new Color(0, 0, 0, 0));
        logBtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        logBtn.setForeground(new java.awt.Color(255, 255, 255));
        logBtn.setText("LOGIN");
        logBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        logBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logBtnMouseExited(evt);
            }
        });
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        loginNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginNameLbl.setText("Nombre:");

        logNameField.setBackground(Color.BLACK);
        logNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logNameField.setForeground(new java.awt.Color(255, 255, 255));
        logNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        logNameField.setMargin(new java.awt.Insets(2, 6, 2, 10));
        logNameField.setMaximumSize(new java.awt.Dimension(64, 26));
        logNameField.setMinimumSize(new java.awt.Dimension(64, 26));
        logNameField.setPreferredSize(new java.awt.Dimension(64, 26));

        loginPassLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginPassLbl.setText("Contraseña:");

        logPassField.setBackground(Color.BLACK);
        logPassField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logPassField.setForeground(new java.awt.Color(255, 255, 255));
        logPassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        logPassField.setMargin(new java.awt.Insets(2, 6, 2, 10));
        logPassField.setMaximumSize(new java.awt.Dimension(64, 26));
        logPassField.setPreferredSize(new java.awt.Dimension(3, 26));

        showLoggedPassword.setBackground(Color.BLACK);
        showLoggedPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showLoggedPassword.setForeground(new java.awt.Color(255, 255, 255));
        showLoggedPassword.setBorder(null);
        showLoggedPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showLoggedPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/eye_close.png"))); // NOI18N
        showLoggedPassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/eye_open.png"))); // NOI18N
        showLoggedPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLoggedPasswordActionPerformed(evt);
            }
        });

        errorLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLbl.setText("    ");
        errorLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        noAccBtn.setBackground(new java.awt.Color(0, 0, 0));
        noAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        noAccBtn.setText("¿NO TIENES UNA CUENTA?");
        noAccBtn.setBorder(null);
        noAccBtn.setBorderPainted(false);
        noAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noAccBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        noAccBtn.setMaximumSize(new java.awt.Dimension(152, 27));
        noAccBtn.setMinimumSize(new java.awt.Dimension(152, 27));
        noAccBtn.setPreferredSize(new java.awt.Dimension(152, 27));
        noAccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noAccBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noAccBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noAccBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                        .addComponent(noAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                        .addComponent(logBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))))
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(logPassField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(errorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(showLoggedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(loginLbl)
                .addGap(59, 59, 59)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginNameLbl)
                    .addComponent(logNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showLoggedPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loginPassLbl)
                        .addComponent(logPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(noAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        regPanel.setBackground(new java.awt.Color(0, 0, 0));
        regPanel.setMaximumSize(new java.awt.Dimension(924, 556));
        regPanel.setMinimumSize(new java.awt.Dimension(924, 556));

        registerLbl.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        registerLbl.setForeground(new java.awt.Color(255, 255, 255));
        registerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLbl.setText("REGISTER");

        hasAccBtn.setBackground(new java.awt.Color(0, 0, 0));
        hasAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        hasAccBtn.setText("¿YA TIENES UNA CUENTA?");
        hasAccBtn.setBorder(null);
        hasAccBtn.setBorderPainted(false);
        hasAccBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hasAccBtn.setFocusPainted(false);
        hasAccBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hasAccBtn.setMaximumSize(new java.awt.Dimension(152, 27));
        hasAccBtn.setMinimumSize(new java.awt.Dimension(152, 27));
        hasAccBtn.setPreferredSize(new java.awt.Dimension(152, 27));
        hasAccBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hasAccBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hasAccBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hasAccBtnMouseExited(evt);
            }
        });

        registerBtn.setBackground(new Color(0, 0, 0, 0));
        registerBtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("REGISTER");
        registerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBtnMouseExited(evt);
            }
        });
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        registerNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        registerNameLbl.setText("Nombre:");

        registerNameField.setBackground(Color.BLACK);
        registerNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registerNameField.setForeground(new java.awt.Color(255, 255, 255));
        registerNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        registerNameField.setMargin(new java.awt.Insets(2, 6, 2, 10));
        registerNameField.setMaximumSize(new java.awt.Dimension(64, 26));
        registerNameField.setMinimumSize(new java.awt.Dimension(64, 26));
        registerNameField.setPreferredSize(new java.awt.Dimension(64, 26));

        newPassField.setBackground(Color.BLACK);
        newPassField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPassField.setForeground(new java.awt.Color(255, 255, 255));
        newPassField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        newPassField.setMargin(new java.awt.Insets(2, 6, 2, 10));
        newPassField.setMaximumSize(new java.awt.Dimension(64, 26));
        newPassField.setPreferredSize(new java.awt.Dimension(3, 26));

        newPassLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        newPassLbl.setText("Contraseña:");

        showPassword.setBackground(Color.BLACK);
        showPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setBorder(null);
        showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/eye_close.png"))); // NOI18N
        showPassword.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/eye_open.png"))); // NOI18N
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        errorRegistrationLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        errorRegistrationLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorRegistrationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorRegistrationLbl.setText("    ");

        javax.swing.GroupLayout regPanelLayout = new javax.swing.GroupLayout(regPanel);
        regPanel.setLayout(regPanelLayout);
        regPanelLayout.setHorizontalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createSequentialGroup()
                        .addComponent(hasAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createSequentialGroup()
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(regPanelLayout.createSequentialGroup()
                                    .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(registerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(5, 5, 5)
                                    .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(registerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(errorRegistrationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createSequentialGroup()
                                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)))
                        .addGap(227, 227, 227))))
        );
        regPanelLayout.setVerticalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(registerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerNameLbl)
                    .addComponent(registerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newPassLbl)
                        .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorRegistrationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(hasAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(logPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(regPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hasAccBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasAccBtnMouseClicked
        logPanel.setVisible(true);
        regPanel.setVisible(false);
    }//GEN-LAST:event_hasAccBtnMouseClicked

    private void hasAccBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasAccBtnMouseEntered
        hasAccBtn.setText("<html><u>¿YA TIENES UNA CUENTA?</u></html>");
    }//GEN-LAST:event_hasAccBtnMouseEntered

    private void hasAccBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasAccBtnMouseExited
        hasAccBtn.setText("¿YA TIENES UNA CUENTA?");
    }//GEN-LAST:event_hasAccBtnMouseExited

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        errorRegistrationLbl.setVisible(false);
        registerNameField.setBorder(new LineBorder(Color.WHITE, 1));
        newPassField.setBorder(new LineBorder(Color.WHITE, 1));

        String nombre = registerNameField.getText();
        char[] pass = newPassField.getPassword();
        String password = new String(pass);
        boolean register = true;
        String error = "";
        if (nombre.isEmpty() || nombre.isBlank()) {
            error += "| Nombre Vacio |";
            registerNameField.setBorder(new LineBorder(Color.RED, 1));
            register = false;
        }
        if (password.isEmpty() || password.isBlank()) {
            if (error.equals("")) {
                error += "| Contraseña Vacia |";
            } else {
                error += "  | Contraseña Vacia |";

            }
            register = false;
            newPassField.setBorder(new LineBorder(Color.RED, 1));
            register = false;
        } else if (password.length() < 8) {
            register = false;
            if (error.equals("")) {
                error += "| Contraseña Corta (Min 8 caracteres) |";
            } else {
                error += "  | Contraseña Corta (Min 8 caracteres) |";
            }
        }

        if (!error.equals("")) {
            errorRegistrationLbl.setText(error);
            errorRegistrationLbl.setVisible(true);
        }

        if (register) {
            Main.users.add(new User(nombre, password));
            JOptionPane.showMessageDialog(this, "Registrado correctamente!\nVuelva a logear...", "REGISTRADO", JOptionPane.INFORMATION_MESSAGE);
            registerNameField.setText("");
            newPassField.setText("");
            int opt = JOptionPane.showConfirmDialog(this, "Deseas Volver al Login?", "", JOptionPane.OK_CANCEL_OPTION);
            if (opt == JOptionPane.OK_OPTION) {
                logPanel.setVisible(true);
                regPanel.setVisible(false);
            }
        }
    }//GEN-LAST:event_registerBtnMouseClicked

    private void registerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseEntered
        registerBtn.setOpaque(true);
        registerBtn.setBackground(Color.WHITE);
        registerBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_registerBtnMouseEntered

    private void registerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseExited
        configBtn(registerBtn);
        registerBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_registerBtnMouseExited

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if (showPassword.isSelected()) {
            newPassField.setEchoChar((char) 0);
        } else {
            newPassField.setEchoChar('•');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void logBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logBtnMouseEntered
        logBtn.setOpaque(true);
        logBtn.setBackground(Color.WHITE);
        logBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_logBtnMouseEntered

    private void logBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logBtnMouseExited
        configBtn(logBtn);
        logBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_logBtnMouseExited

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        registerNameField.setBorder(new LineBorder(Color.WHITE, 1));
        newPassField.setBorder(new LineBorder(Color.WHITE, 1));
        User user = null;
        String nombre = logNameField.getText();
        char[] pass = logPassField.getPassword();
        String password = new String(pass);
        boolean login = true;
        String error = "";
        if (nombre.isEmpty() || nombre.isBlank()) {
            error += "| Nombre Vacio |";
            registerNameField.setBorder(new LineBorder(Color.RED, 1));
            login = false;
        }
        if (password.isEmpty() || password.isBlank()) {
            if (error.equals("")) {
                error += "| Contraseña Vacia |";
            } else {
                error += "  | Contraseña Vacia |";
            }

            newPassField.setBorder(new LineBorder(Color.RED, 1));
            login = false;
        }
        if (login) {
            user = buscarUsuario(nombre, password);
        } else {
            errorRegistrationLbl.setVisible(true);
            errorRegistrationLbl.setText(error);
        }

        if (user != null) {
            Dashboard dash = new Dashboard(user);
            dash.setVisible(true);
            dash.setLocationRelativeTo(null);
            this.dispose();
        } else {
            errorRegistrationLbl.setText("");
            JOptionPane.showMessageDialog(this, "Usuario no encontrado!", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logBtnActionPerformed

    private void showLoggedPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLoggedPasswordActionPerformed
        if (showLoggedPassword.isSelected()) {
            logPassField.setEchoChar((char) 0);
        } else {
            logPassField.setEchoChar('•');
        }
    }//GEN-LAST:event_showLoggedPasswordActionPerformed

    private void noAccBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noAccBtnMouseClicked
        logPanel.setVisible(false);
        regPanel.setVisible(true);
    }//GEN-LAST:event_noAccBtnMouseClicked

    private void noAccBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noAccBtnMouseEntered
        hasAccBtn.setText("<html><u>¿NO TIENES UNA CUENTA?</u></html>");
    }//GEN-LAST:event_noAccBtnMouseEntered

    private void noAccBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noAccBtnMouseExited
        hasAccBtn.setText("¿NO TIENES UNA CUENTA?");
    }//GEN-LAST:event_noAccBtnMouseExited

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel errorRegistrationLbl;
    private javax.swing.JButton hasAccBtn;
    private javax.swing.JButton logBtn;
    private javax.swing.JTextField logNameField;
    private javax.swing.JPanel logPanel;
    private javax.swing.JPasswordField logPassField;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JLabel loginNameLbl;
    private javax.swing.JLabel loginPassLbl;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JButton noAccBtn;
    private javax.swing.JPanel regPanel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JTextField registerNameField;
    private javax.swing.JLabel registerNameLbl;
    private javax.swing.JCheckBox showLoggedPassword;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables
}
